environment:

  global:
    CYG_ROOT: C:\\cygwin

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      TOX_APPVEYOR_X64: 0

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      TOX_APPVEYOR_X64: 0

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      TOX_APPVEYOR_X64: 0

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      TOX_APPVEYOR_X64: 0

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      TOX_APPVEYOR_X64: 0

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      TOX_APPVEYOR_X64: 1

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      TOX_APPVEYOR_X64: 1

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      TOX_APPVEYOR_X64: 1

build: off
os: unstable  # http://help.appveyor.com/discussions/suggestions/427-pre-install-cygwin

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

# pip is used to prepare testtools because otherwise pbr fails during the
# testscenarios install with 'The filename or extension is too long'.
install:
  - "%PYTHON%\\Scripts\\pip.exe install tox tox-appveyor"

# geventhttpclient fails to build:
# https://github.com/gwik/geventhttpclient/issues/65
# On Win64 Appveyor, pip cant install win64 builds of pycurl, and pycurl setup.py
# cant find curl headers in the build environment.
test_script:
  - "%PYTHON%\\python -m tox -e nocurl"
