# codecov-python has no Cirrus CI support
# https://github.com/codecov/codecov-python/issues/233
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  CODECOV_TOKEN: ENCRYPTED[64e5d3e11afe49721bbc6fc0acd9df6e05e829f8b207e267fd13882fb4518b59d68b030b610b7af4c6f7268ad9fb4414]

Linux_task:
  container:
    matrix:
      - image: python:2.7
      - image: python:3.4
      - image: python:3.5
      - image: python:3.8
  install_script:
    - pip install -U tox git+https://github.com/jayvdb/tox-add-factor@with-tox-travis
  script:
    - python --version
    - PY=$(python -c 'import sys; print("%d%d" % (sys.version_info[0], sys.version_info[1]))')
    - python -m tox -e py$PY --prepend-username-factor --prepend-ostype-factor --prepend-archraw-factor --prepend-cpuarch-factor

macOS_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install python3
    - pip3 install -U tox git+https://github.com/jayvdb/tox-add-factor@with-tox-travis
  script:
    - python3 --version
    - PY=$(python3 -c 'import sys; print("%d%d" % (sys.version_info[0], sys.version_info[1]))')
    - python3 -m tox -e py$PY --prepend-username-factor --prepend-ostype-factor --prepend-archraw-factor --prepend-cpuarch-factor

Windows_task:
  windows_container:
    os_version: 2019
    matrix:
      - image: python:3.8-windowsservercore-1809
  install_script:
    - C:\Python\python.exe -m pip install -U tox git+https://github.com/jayvdb/tox-add-factor@with-tox-travis
  script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe -m tox --prepend-username-factor --append-factor nocurl --append-factor nocurl --prepend-ostype-factor --prepend-archraw-factor --prepend-cpuarch-factor
