language: python

python:
  - '2.7'
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'
  - 'pypy'

addons:
  apt:
    packages:
      - gnutls-dev

install:
  - python -c "import setuptools; print(setuptools.__version__)"
  - case ${TRAVIS_PYTHON_VERSION} in 2.6|2.7|pypy) pip install cryptography pyasn1 pyasn1-modules unittest2 ;; esac

  - pip install tox-travis tox-add-factor

script:
  - tox --prepend-username-factor --prepend-ostype-factor --prepend-archraw-factor --prepend-cpuarch-factor --add-ci-factor
